import React, { memo } from 'react';
import { RemoteConfig, RemoteButton } from '../types/remote';
import { RemoteDispatcher } from '../services/remoteDispatcher';

interface DynamicRemoteProps {
  config: RemoteConfig;
    onBack: () => void;
      isFavorite?: boolean;
        onToggleFavorite?: (config: RemoteConfig) => void;
        }

        export const DynamicRemote: React.FC<DynamicRemoteProps> = memo(({
          config,
            onBack,
              isFavorite = false,
                onToggleFavorite
                }) => {
                  const handlePress = async (btn: RemoteButton) => {
                      if (typeof window !== 'undefined' && window.navigator && window.navigator.vibrate) {
                            window.navigator.vibrate(35);
                                }

                                    await RemoteDispatcher.sendSignal({
                                          code: btn.code,
                                                protocol: config.protocol,
                                                      frequency: config.frequency,
                                                            ipEndpoint: config.ipEndpoint
                                                                });
                                                                  };

                                                                    return (
                                                                        <div className="w-full max-w-md mx-auto bg-slate-900 border border-cyan-500/20 rounded-3xl p-6 shadow-2xl">
                                                                              {/* Header Bar */}
                                                                                    <div className="flex justify-between items-center mb-6 border-b border-slate-800 pb-4">
                                                                                            <button
                                                                                                      onClick={onBack}
                                                                                                                className="px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-sm transition-all"
                                                                                                                        >
                                                                                                                                  ← عودة
                                                                                                                                          </button>

                                                                                                                                                  <div className="text-center">
                                                                                                                                                            <h3 className="text-xl font-bold text-cyan-400 capitalize">{config.brandId}</h3>
                                                                                                                                                                      <span className="text-xs text-slate-400 uppercase tracking-wider">{config.categoryId}</span>
                                                                                                                                                                              </div>

                                                                                                                                                                                      {onToggleFavorite ? (
                                                                                                                                                                                                <button
                                                                                                                                                                                                            onClick={() => onToggleFavorite(config)}
                                                                                                                                                                                                                        className={`p-2 rounded-xl transition-all ${
                                                                                                                                                                                                                                      isFavorite ? 'text-amber-400 bg-amber-400/10' : 'text-slate-500 hover:text-slate-300 bg-slate-800'
                                                                                                                                                                                                                                                  }`}
                                                                                                                                                                                                                                                              title="إضافة للمفضلة"
                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                    ★
                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                <div className="w-8" />
                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                    {/* Dynamic Button Grid */}
                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-3 gap-3">
                                                                                                                                                                                                                                                                                                                                                  {config.buttons.map((btn) => {
                                                                                                                                                                                                                                                                                                                                                            const isPower = btn.id === 'power';
                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                key={btn.id}
                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => handlePress(btn)}
                                                                                                                                                                                                                                                                                                                                                                                                                            className={`
                                                                                                                                                                                                                                                                                                                                                                                                                                            h-16 rounded-2xl font-bold text-sm flex flex-col items-center justify-center 
                                                                                                                                                                                                                                                                                                                                                                                                                                                            transition-all active:scale-95 select-none shadow-md
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ${isPower 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? 'col-span-3 bg-red-600 hover:bg-red-500 text-white shadow-red-900/30' 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : 'bg-slate-800 hover:bg-slate-700 text-slate-100 border border-slate-700/50'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              `}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>{btn.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  DynamicRemote.displayName = 'DynamicRemote';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  